name: Hexo_CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download Source file
      uses: actions/checkout@v2
      with:
        ref: main # 此处修改为自己存放 Hexo 源文件的分支

    - name: Prepare Node env
      uses: actions/setup-node@v1
      with:
        node-version: "10.x" # 此处和自己的nodejs版本对应(10,12测试成功)

    - name: Set Env
      env: 
        GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  
      run: |
        git config --global user.name 'Hoshi' # github用户名
        git config --global user.email '21078047+MeowCheng@users.noreply.github.com' # github邮箱
        sed -i "s/GITHUB_ACCESS_TOKEN/$GITHUB_ACCESS_TOKEN/g" ./_config.yml
    - name: Hexo
      run: |
        npm install hexo
        npm install
        npx hexo clean
        npx hexo g -d
